main: io.izzel.mesmerize.impl.Mesmerize
name: Mesmerize
version: ${version}
authors: [IzzelAliz]
website: www.mcbbs.net/thread-779975-1-1.html
softdepend:
  - RPGInventory
  - PlaceholderAPI
  - Citizens
  - Vault
commands:
  mes:
    usage: /mes
    description: /mes
  mesmerize:
    usage: /mes
    description: /mes
permissions:
  mesmerize.showstats:
    default: true
  mesmerize.evaluate:
    default: true
  mesmerize.config:
    default: op
  mesmerize.sell:
    default: true